name: 'Deploy production on firebase'

on:
  release:
    types: [created]

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: checking repository out
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          path: .

      - name: Use Node.js '16.x'
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: installing npm dependencies
        run: npm install
      
      - name: build app
        run: CI=false npm run build
        
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.DEPLOY_PREVIEW_FIREBASE_TOKEN }}
