name: 'Deploy preview on firebase'

on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest      
    steps:

    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        path: .

    - run: mkdir ./build
    - run: docker-compose -f docker-compose-build-app.yml up -d

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: hosting:channel:deploy save-load-hwstatus
      env:
        FIREBASE_TOKEN: ${{ secrets.DEPLOY_PREVIEW_FIREBASE_TOKEN }}