name: Deploy Preview Firebase on workflow_dispatch
on: workflow_dispatch
jobs:
  build_and_preview:
    env:
        CHANNEL: 'build'
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i && CI=false npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TESTING_PLATFORM_90B5B }}'
          projectId: testing-platform-90b5b
          channelID: ${{ env.CHANNEL }}
