name: Deploy to Production Firebase on Release
on:
  release:
    types: [created]
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i && CI=false npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TESTING_PLATFORM_90B5B }}'
          projectId: testing-platform-90b5b
          channelID: live
